name: avalon_app
description: "AvalonPlus"
publish_to: "none"
version: 1.0.1+101

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  another_flushbar: ^1.12.30
  authentication_repository:
    path: packages/authentication_repository
  cache:
    path: packages/cache
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^13.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.3.0
  pull_to_refresh: ^2.0.0
  shared_models:
    path: packages/shared_models
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.31.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/Isotipo3.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/logos/
    # - assets/icons/
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
